
services:
  mongodb:
    image: mongo:latest
    container_name: pokemon-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: